# Covid file scrubbing

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [2]:
# Dependencies and Setup
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# File to Load (Remember to Change These)
covid19_data_to_load = "Data/covid19_data.csv"
centroid_data_to_load = "Data/country_centroids_az8.csv"
pop_data_to_load = "Data/pop_data_2009-2019.csv"

# Read School and Student Data File and store into Pandas Data Frames
#covid19_data = pd.read_csv(swineflu_data_to_load, encoding=”ISO-8859–1”)
covid19_data = pd.read_csv(covid19_data_to_load, encoding="ISO-8859-1")
centroid_data = pd.read_csv(centroid_data_to_load)
pop_data = pd.read_csv(pop_data_to_load)

In [3]:
# remove spaces and '.' in column names
covid19_data.columns = [c.replace(' ', '_') for c in covid19_data.columns]
covid19_data.columns = [c.replace('.', '') for c in covid19_data.columns]

# Find earliest and latest dates
print(covid19_data.Date.min())
print(covid19_data.Date.max())
covid19_data

1/22/2020
3/9/2020

     Pandemic       Date      Country  Cases  Deaths
0     covid19  2/24/2020  Afghanistan      1       0
1     covid19  2/25/2020  Afghanistan      1       0
2     covid19  2/26/2020  Afghanistan      1       0
3     covid19  2/27/2020  Afghanistan      1       0
4     covid19  2/28/2020  Afghanistan      1       0
...       ...        ...          ...    ...     ...
8504  covid19  3/20/2020     Zimbabwe      1       0
8505  covid19  3/21/2020     Zimbabwe      3       0
8506  covid19  3/22/2020     Zimbabwe      3       0
8507  covid19  3/23/2020     Zimbabwe      3       1
8508  covid19  3/24/2020     Zimbabwe      3       1

[8509 rows x 5 columns]

In [4]:
# Add year column to dataframe
covid19_data['Year'] = pd.DatetimeIndex(covid19_data['Date']).year
covid19_data

     Pandemic       Date      Country  Cases  Deaths  Year
0     covid19  2/24/2020  Afghanistan      1       0  2020
1     covid19  2/25/2020  Afghanistan      1       0  2020
2     covid19  2/26/2020  Afghanistan      1       0  2020
3     covid19  2/27/2020  Afghanistan      1       0  2020
4     covid19  2/28/2020  Afghanistan      1       0  2020
...       ...        ...          ...    ...     ...   ...
8504  covid19  3/20/2020     Zimbabwe      1       0  2020
8505  covid19  3/21/2020     Zimbabwe      3       0  2020
8506  covid19  3/22/2020     Zimbabwe      3       0  2020
8507  covid19  3/23/2020     Zimbabwe      3       1  2020
8508  covid19  3/24/2020     Zimbabwe      3       1  2020

[8509 rows x 6 columns]

In [5]:
covid19_data['Country'].value_counts()

China                                 1951
United States of America              1738
Australia                              340
Canada                                 280
France                                 147
United Kingdom                         109
Thailand                                63
China, Macao SAR                        63
China, Taiwan Province of China         63
Japan                                   63
Republic of Korea                       63
China, Hong Kong SAR                    63
Singapore                               62
Viet Nam                                62
Malaysia                                61
Nepal                                   60
Sri Lanka                               58
Cambodia                                58
Italy                                   58
Germany                                 57
Philippines                             56
Finland                                 56
United Arab Emirates                    56
India                                   55
Russian Federation                      54
Sweden                                  54
Spain                                   53
Belgium                                 50
Netherlands                             48
Denmark                                 47
Others                                  46
Egypt                                   40
Iran (Islamic Republic of)              35
Israel                                  33
Lebanon                                 33
Iraq                                    31
Bahrain                                 30
Oman                                    30
Kuwait                                  30
Afghanistan                             30
Switzerland                             29
Brazil                                  29
Croatia                                 29
Algeria                                 29
Austria                                 29
Greece                                  28
Georgia                                 28
Romania                                 28
North Macedonia                         28
Norway                                  28
Pakistan                                28
Estonia                                 27
Mexico                                  27
San Marino                              27
New Zealand                             26
Belarus                                 26
Nigeria                                 26
Ireland                                 26
Lithuania                               26
Iceland                                 26
Azerbaijan                              25
Luxembourg                              25
Monaco                                  25
Qatar                                   25
Armenia                                 24
Czechia                                 24
Dominican Republic                      24
Ecuador                                 24
Indonesia                               23
Latvia                                  23
Portugal                                23
Andorra                                 23
Saudi Arabia                            23
Senegal                                 23
Morocco                                 23
Argentina                               22
Jordan                                  22
Ukraine                                 22
Chile                                   22
Poland                                  21
Liechtenstein                           21
Tunisia                                 21
Hungary                                 21
Slovenia                                20
South Africa                            20
Colombia                                20
Bosnia and Herzegovina                  20
Togo                                    19
Costa Rica                              19
Bhutan                                  19
Slovakia                                19
Serbia                                  19
Cameroon                                19
Peru                                    19
Malta                                   18
Paraguay                                17
Maldives                                17
Republic of Moldova                     17
Bulgaria                                17
Bangladesh                              17
Congo                                   16
Cyprus                                  16
Albania                                 16
Brunei Darussalam                       16
CÃ´te d'Ivoire                          15
Martinique                              15
Burkina Faso                            15
Holy See                                15
Mongolia                                15
Panama                                  15
Honduras                                14
French Guiana                           14
Turkey                                  14
Bolivia (Plurinational State of)        14
Jamaica                                 14
Democratic Republic of the Congo        14
Cuba                                    13
Guyana                                  13
Kenya                                   12
Gambia                                  12
Guinea                                  12
Bahamas                                 12
Ethiopia                                12
Kazakhstan                              12
Antigua and Barbuda                     12
Sudan                                   12
Namibia                                 11
Mauritania                              11
Eswatini                                11
Saint Vincent and the Grenadines        11
Suriname                                11
Rwanda                                  11
Trinidad and Tobago                     11
Ghana                                   11
Reunion                                 11
Guatemala                               11
Gabon                                   11
Uruguay                                 11
Venezuela (Bolivarian Republic of)      11
Saint Lucia                             11
Seychelles                              11
Central African Republic                10
Uzbekistan                              10
Equatorial Guinea                       10
United Republic of Tanzania              9
Liberia                                  9
Somalia                                  9
Benin                                    9
Guadeloupe                               9
Montenegro                               8
Guernsey                                 8
Jersey                                   8
Barbados                                 8
Djibouti                                 7
Aruba                                    7
Kyrgyzstan                               7
Faroe Islands                            7
State of Palestine                       7
Mauritius                                7
Gibraltar                                7
Zambia                                   7
Saint BarthÃ©lemy                        7
Kosovo                                   7
Puerto Rico                              6
El Salvador                              6
Chad                                     6
Nicaragua                                6
Guam                                     6
Fiji                                     6
Mayotte                                  6
Greenland                                6
Cabo Verde                               6
Papua New Guinea                         5
Haiti                                    5
Palestine                                5
Madagascar                               5
Niger                                    5
Angola                                   5
Zimbabwe                                 5
Uganda                                   4
Eritrea                                  4
Timor-Leste                              4
Dominica                                 3
Syrian Arab Republic                     3
Grenada                                  3
Mozambique                               3
Cayman Islands                           3
Saint Martin (French part)               2
Belize                                   2
CuraÃ§ao                                 2
Channel Islands                          1
North Ireland                            1
Lao People's Democratic Republic         1
Libya                                    1
Name: Country, dtype: int64

In [ ]:
# covid19_data_1 .insert(0,"Pandemic", "covid19")

In [ ]:
# Group by country and year (I think there's only one year, but just in case...)
covid19_data_1 = covid19_data.groupby(["Country", "Year"], as_index = False).agg(
    {
        'Cases':'sum',    
        'Deaths': 'sum'
    }
)

covid19_data_1

In [ ]:
# Merge longitude and latitude data by country
# Get name, Longitude, and Latitude from centroid_data
centroid_data_1 = centroid_data[['name', 'Longitude', 'Latitude']]
centroid_data_2 = centroid_data_1['name'].replace(['United States'], 'United States of America')
centroid_data_2

In [ ]:
# Merge centroid lon, lat 
covid19_2 = pd.merge(covid19_data_1 , centroid_data_1, left_on='Country', right_on='name', how = 'left')
covid19_2

In [ ]:
# Get subset of pop_data, Country, 2014, 2015, 2016
pop_data_1 = pop_data[['Country', '2016']]
pop_data_1

In [ ]:
# Merge Population Data
# Merge centroid lon, lat 
covid19_3 = pd.merge(covid19_2, pop_data_1, on='Country', how = 'left')
covid19_3

In [ ]:
covid19_3['population'] = covid19_3['2016'] * 1000 
covid19_3

In [ ]:
covid19_3.columns

In [ ]:
covid19_4 = covid19_3.rename(columns={"year": "Year", "Longitude": "Lon", "Latitude": "Lat" })
covid19_4

In [ ]:
covid19_5 = covid19_4.drop(columns=['2016'])

In [ ]:
covid19_5

In [ ]:
covid19_5['Pandemic'] = "covid19"
covid19_5

In [ ]:
covid19_5.to_csv(r'Data/merged_covid_19_data.csv', index = False, header=True)

## Send this to sql lite Create database connection

In [ ]:
covid19_5.tosqlite("covid19_data.sql")