### Notebook to scrub ebola dataset for Project 2

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# File to Load (Remember to Change These)
ebola_data_to_load = "Data/ebola_2014_2016_clean.csv"
centroid_data_to_load = "Data/country_centroids_az8.csv"
pop_data_to_load = "Data/pop_data_2009-2019.csv"

# Read Population Data from "Estimates" sheet
ebola_data = pd.read_csv(ebola_data_to_load, encoding="ISO-8859-1")
centroid_data = pd.read_csv(centroid_data_to_load)
pop_data = pd.read_csv(pop_data_to_load)

In [2]:
# remove spaces and '.' in column names
ebola_data.columns = [c.replace(' ', '_') for c in ebola_data.columns]
ebola_data.columns = [c.replace('.', '') for c in ebola_data.columns]

# Add year column to dataframe
ebola_data['year'] = pd.DatetimeIndex(ebola_data['Date']).year

# Find earliest and latest dates
print(ebola_data.Date.min())
print(ebola_data.Date.max())
ebola_data

2014-08-29
2016-03-23

                       Country        Date  No_of_suspected_cases  No_of_probable_cases  No_of_confirmed_cases  No_of_confirmed,_probable_and_suspected_cases  No_of_suspected_deaths  No_of_probable_deaths  No_of_confirmed_deaths  No_of_confirmed,_probable_and_suspected_deaths  year
0                       Guinea  2014-08-29                   25.0                 141.0                  482.0                                          648.0                     2.0                  141.0                   287.0                                           430.0  2014
1                      Nigeria  2014-08-29                    3.0                   1.0                   15.0                                           19.0                     0.0                    1.0                     6.0                                             7.0  2014
2                 Sierra Leone  2014-08-29                   54.0                  37.0                  935.0                                         1026.0                     8.0                   34.0                   380.0                                           422.0  2014
3                      Liberia  2014-08-29                  382.0                 674.0                  322.0                                         1378.0                   168.0                  301.0                   225.0                                           694.0  2014
4                 Sierra Leone  2014-09-05                   78.0                  37.0                 1146.0                                         1261.0                    11.0                   37.0                   443.0                                           491.0  2014
...                        ...         ...                    ...                   ...                    ...                                            ...                     ...                    ...                     ...                                             ...   ...
2480                   Liberia  2016-03-23                 5636.0                1879.0                 3151.0                                        10666.0                     NaN                    NaN                     NaN                                          4806.0  2016
2481                     Italy  2016-03-23                    0.0                   0.0                    1.0                                            1.0                     NaN                    NaN                     NaN                                             0.0  2016
2482                   Liberia  2016-03-23                    0.0                   3.0                    2.0                                            5.0                     NaN                    3.0                     1.0                                             4.0  2016
2483                   Nigeria  2016-03-23                    0.0                   1.0                   19.0                                           20.0                     0.0                    1.0                     7.0                                             8.0  2016
2484  United States of America  2016-03-23                    0.0                   0.0                    4.0                                            4.0                     0.0                    0.0                     1.0                                             1.0  2016

[2485 rows x 11 columns]

In [3]:
# How many occurrences of each country in dataset?
ebola_data['Country'].value_counts()

Liberia                     365
Sierra Leone                259
Guinea                      259
Nigeria                     255
Senegal                     254
United States of America    245
Mali                        243
Spain                       243
United Kingdom              221
Italy                       141
Name: Country, dtype: int64

In [4]:
# Group by country and year
ebola_1 = ebola_data.groupby(["Country", "year"], as_index = False).agg(
    {
        'No_of_confirmed_cases':'sum',    
        'No_of_confirmed_deaths': 'sum'
    }
)

ebola_1

                     Country  year  No_of_confirmed_cases  No_of_confirmed_deaths
0                     Guinea  2014                56295.0                 31014.0
1                     Guinea  2015               689976.0                428114.0
2                     Guinea  2016                 3351.0                  2083.0
3                      Italy  2015                  140.0                     0.0
4                      Italy  2016                    1.0                     0.0
5                    Liberia  2014                72254.0                 11385.0
6                    Liberia  2015               693322.0                 15548.0
7                    Liberia  2016                 3162.0                     4.0
8                       Mali  2014                  111.0                    21.0
9                       Mali  2015                 1540.0                     0.0
10                      Mali  2016                    7.0                     0.0
11                   Nigeria  2014                  717.0                   265.0
12                   Nigeria  2015                 4104.0                  1512.0
13                   Nigeria  2016                   19.0                     7.0
14                   Senegal  2014                   37.0                     0.0
15                   Senegal  2015                  216.0                     0.0
16                   Senegal  2016                    1.0                     0.0
17              Sierra Leone  2014               156787.0                 41981.0
18              Sierra Leone  2015              1876380.0                752414.0
19              Sierra Leone  2016                 8704.0                  3589.0
20                     Spain  2014                   26.0                     0.0
21                     Spain  2015                  216.0                     0.0
22                     Spain  2016                    1.0                     0.0
23            United Kingdom  2015                  220.0                     0.0
24            United Kingdom  2016                    1.0                     0.0
25  United States of America  2014                   99.0                    25.0
26  United States of America  2015                  864.0                   216.0
27  United States of America  2016                    4.0                     1.0

In [5]:
# Merge longitude and latitude data by country
# Get name, Longitude, and Latitude from centroid_data
centroid_data_1 = centroid_data[['name', 'Longitude', 'Latitude']]
centroid_data_2 = centroid_data_1['name'].replace(['United States'], 'United States of America')
centroid_data_2

0                          Aruba
1                    Afghanistan
2                         Angola
3                       Anguilla
4                        Albania
5                          Aland
6                        Andorra
7           United Arab Emirates
8                      Argentina
9                        Armenia
10                American Samoa
11                    Antarctica
12       Ashmore and Cartier Is.
13        Fr. S. Antarctic Lands
14             Antigua and Barb.
15                     Australia
16                       Austria
17                    Azerbaijan
18                       Burundi
19                       Belgium
20                         Benin
21                  Burkina Faso
22                    Bangladesh
23                      Bulgaria
24                       Bahrain
25                        Canada
26                       Bahamas
27              Bosnia and Herz.
28                St-BarthÃƒÂ©lemy
29                       Belarus
30                        Belize
31                       Bermuda
32                       Bolivia
33                        Brazil
34                      Barbados
35                        Brunei
36                        Bhutan
37                      Botswana
38          Central African Rep.
39                   Switzerland
40                         Chile
41                         China
42                CÃƒÂ´te d'Ivoire
43                      Cameroon
44               Dem. Rep. Congo
45                         Congo
46                      Cook Is.
47                      Colombia
48                       Comoros
49                    Cape Verde
50                    Costa Rica
51                          Cuba
52                      CuraÃƒÂ§ao
53                    Cayman Is.
54                     N. Cyprus
55                        Cyprus
56                    Czech Rep.
57                       Germany
58                      Djibouti
59                      Dominica
60                       Denmark
61                Dominican Rep.
62                       Algeria
63                       Ecuador
64                         Egypt
65                       Eritrea
66                         Spain
67                       Estonia
68                      Ethiopia
69                       Finland
70                          Fiji
71                  Falkland Is.
72                        France
73                    Faeroe Is.
74                    Micronesia
75                         Gabon
76                United Kingdom
77                       Georgia
78                      Guernsey
79                         Ghana
80                        Guinea
81                        Gambia
82                 Guinea-Bissau
83                    Eq. Guinea
84                        Greece
85                       Grenada
86                     Greenland
87                     Guatemala
88                          Guam
89                        Guyana
90                     Hong Kong
91     Heard I. and McDonald Is.
92                      Honduras
93                       Croatia
94                         Haiti
95                       Hungary
96                     Indonesia
97                   Isle of Man
98                         India
99             Indian Ocean Ter.
100        Br. Indian Ocean Ter.
101                      Ireland
102                         Iran
103                         Iraq
104                      Iceland
105                       Israel
106                        Italy
107                      Jamaica
108                       Jersey
109                       Jordan
110                        Japan
111              Siachen Glacier
112                   Kazakhstan
113                        Kenya
114                   Kyrgyzstan
115                     Cambodia
116                     Kiribati
117          St. Kitts and Nevis
118                        Korea
119                       Kosovo
120                       Kuwait
121                      Lao PDR
122                      Lebanon
123                      Liberia
124                        Libya
125                  Saint Lucia
126                Liechtenstein
127                    Sri Lanka
128                      Lesotho
129                    Lithuania
130                   Luxembourg
131                       Latvia
132                        Macao
133                    St-Martin
134                      Morocco
135                       Monaco
136                      Moldova
137                   Madagascar
138                     Maldives
139                       Mexico
140                 Marshall Is.
141                    Macedonia
142                         Mali
143                        Malta
144                      Myanmar
145                   Montenegro
146                     Mongolia
147               N. Mariana Is.
148                   Mozambique
149                   Mauritania
150                   Montserrat
151                    Mauritius
152                       Malawi
153                     Malaysia
154                      Namibia
155                New Caledonia
156                        Niger
157               Norfolk Island
158                      Nigeria
159                    Nicaragua
160                         Niue
161                  Netherlands
162                       Norway
163                        Nepal
164                        Nauru
165                  New Zealand
166                         Oman
167                     Pakistan
168                       Panama
169                 Pitcairn Is.
170                         Peru
171                  Philippines
172                        Palau
173             Papua New Guinea
174                       Poland
175                  Puerto Rico
176              Dem. Rep. Korea
177                     Portugal
178                     Paraguay
179                    Palestine
180                Fr. Polynesia
181                        Qatar
182                      Romania
183                       Russia
184                       Rwanda
185                    W. Sahara
186                 Saudi Arabia
187                        Sudan
188                     S. Sudan
189                      Senegal
190                    Singapore
191    S. Geo. and S. Sandw. Is.
192                 Saint Helena
193                  Solomon Is.
194                 Sierra Leone
195                  El Salvador
196                   San Marino
197                   Somaliland
198                      Somalia
199      St. Pierre and Miquelon
200                       Serbia
201      SÃƒÂ£o TomÃƒÂ© and Principe
202                     Suriname
203                     Slovakia
204                     Slovenia
205                       Sweden
206                    Swaziland
207                 Sint Maarten
208                   Seychelles
209                        Syria
210         Turks and Caicos Is.
211                         Chad
212                         Togo
213                     Thailand
214                   Tajikistan
215                 Turkmenistan
216                  Timor-Leste
217                        Tonga
218          Trinidad and Tobago
219                      Tunisia
220                       Turkey
221                       Taiwan
222                     Tanzania
223                       Uganda
224                      Ukraine
225                      Uruguay
226     United States of America
227                   Uzbekistan
228                      Vatican
229           St. Vin. and Gren.
230                    Venezuela
231           British Virgin Is.
232              U.S. Virgin Is.
233                      Vietnam
234                      Vanuatu
235        Wallis and Futuna Is.
236                        Samoa
237                        Yemen
238                 South Africa
239                       Zambia
240                     Zimbabwe
Name: name, dtype: object

In [6]:
# Merge centroid lon, lat 
ebola_2 = pd.merge(ebola_1, centroid_data_1, left_on='Country', right_on='name', how = 'left')
ebola_2

                     Country  year  No_of_confirmed_cases  No_of_confirmed_deaths            name  Longitude   Latitude
0                     Guinea  2014                56295.0                 31014.0          Guinea -10.940666  10.436216
1                     Guinea  2015               689976.0                428114.0          Guinea -10.940666  10.436216
2                     Guinea  2016                 3351.0                  2083.0          Guinea -10.940666  10.436216
3                      Italy  2015                  140.0                     0.0           Italy  12.070013  42.796626
4                      Italy  2016                    1.0                     0.0           Italy  12.070013  42.796626
5                    Liberia  2014                72254.0                 11385.0         Liberia  -9.322076   6.452785
6                    Liberia  2015               693322.0                 15548.0         Liberia  -9.322076   6.452785
7                    Liberia  2016                 3162.0                     4.0         Liberia  -9.322076   6.452785
8                       Mali  2014                  111.0                    21.0            Mali  -3.542691  17.345816
9                       Mali  2015                 1540.0                     0.0            Mali  -3.542691  17.345816
10                      Mali  2016                    7.0                     0.0            Mali  -3.542691  17.345816
11                   Nigeria  2014                  717.0                   265.0         Nigeria   8.089439   9.594115
12                   Nigeria  2015                 4104.0                  1512.0         Nigeria   8.089439   9.594115
13                   Nigeria  2016                   19.0                     7.0         Nigeria   8.089439   9.594115
14                   Senegal  2014                   37.0                     0.0         Senegal -14.473492  14.366242
15                   Senegal  2015                  216.0                     0.0         Senegal -14.473492  14.366242
16                   Senegal  2016                    1.0                     0.0         Senegal -14.473492  14.366242
17              Sierra Leone  2014               156787.0                 41981.0    Sierra Leone -11.792712   8.563296
18              Sierra Leone  2015              1876380.0                752414.0    Sierra Leone -11.792712   8.563296
19              Sierra Leone  2016                 8704.0                  3589.0    Sierra Leone -11.792712   8.563296
20                     Spain  2014                   26.0                     0.0           Spain  -3.647550  40.244487
21                     Spain  2015                  216.0                     0.0           Spain  -3.647550  40.244487
22                     Spain  2016                    1.0                     0.0           Spain  -3.647550  40.244487
23            United Kingdom  2015                  220.0                     0.0  United Kingdom  -2.865632  54.123872
24            United Kingdom  2016                    1.0                     0.0  United Kingdom  -2.865632  54.123872
25  United States of America  2014                   99.0                    25.0             NaN        NaN        NaN
26  United States of America  2015                  864.0                   216.0             NaN        NaN        NaN
27  United States of America  2016                    4.0                     1.0             NaN        NaN        NaN

In [7]:
# Get subset of pop_data, Country, 2014, 2015, 2016
pop_data_1 = pop_data[['Country', '2014', '2015', '2016']]
pop_data_1

                                Country         2014         2015         2016
0                                 WORLD  7295290.759  7379796.967  7464021.934
1                               Burundi     9844.301    10160.034    10488.002
2                               Comoros      759.390      777.435      795.597
3                              Djibouti      898.707      913.998      929.117
4                               Eritrea     3311.444     3342.818     3376.558
5                              Ethiopia    98094.264   100835.453   103603.461
6                                 Kenya    46700.063    47878.339    49051.531
7                            Madagascar    23589.897    24234.080    24894.370
8                                Malawi    16289.550    16745.305    17205.253
9                             Mauritius     1257.351     1259.457     1261.870
10                              Mayotte      233.658      240.011      246.460
11                           Mozambique    26286.192    27042.001    27829.930
12                              RÃ©union      856.960      863.359      869.742
13                               Rwanda    11083.629    11369.066    11668.829
14                           Seychelles       94.214       94.981       95.711
15                              Somalia    13423.571    13797.204    14185.635
16                          South Sudan    10554.882    10715.657    10832.520
17                               Uganda    36911.530    38225.447    39649.173
18          United Republic of Tanzania    49960.563    51482.638    53049.231
19                               Zambia    15399.793    15879.370    16363.449
20                             Zimbabwe    13586.710    13814.642    14030.338
21                               Angola    26941.773    27884.380    28842.482
22                             Cameroon    22681.853    23298.376    23926.549
23             Central African Republic     4464.171     4493.171     4537.683
24                                 Chad    13663.562    14110.971    14561.658
25                                Congo     4736.965     4856.093     4980.996
26     Democratic Republic of the Congo    73767.445    76244.532    78789.130
27                    Equatorial Guinea     1122.273     1168.575     1215.181
28                                Gabon     1883.801     1947.690     2007.882
29                Sao Tome and Principe      195.727      199.439      203.221
30                             Botswana     2088.619     2120.716     2159.925
31                             Eswatini     1095.022     1104.038     1113.994
32                              Lesotho     2043.448     2059.011     2075.041
33                              Namibia     2273.426     2314.901     2358.044
34                         South Africa    54544.184    55386.369    56207.649
35                                Benin    10286.839    10575.962    10872.072
36                         Burkina Faso    17586.029    18110.616    18646.350
37                           Cabo Verde      518.276      524.740      531.140
38                        CÃ´te d'Ivoire    22647.672    23226.148    23822.726
39                               Gambia     2024.037     2085.860     2149.134
40                                Ghana    27224.480    27849.203    28481.947
41                               Guinea    11150.970    11432.096    11738.434
42                        Guinea-Bissau     1692.433     1737.207     1782.434
43                              Liberia     4359.508     4472.229     4586.788
44                                 Mali    16934.213    17438.772    17965.448
45                           Mauritania     3930.894     4046.304     4163.532
46                                Niger    19240.182    20001.663    20788.789
47                              Nigeria   176404.931   181137.454   185960.244
48                         Saint Helena        5.737        5.869        5.958
49                              Senegal    14174.740    14578.450    14993.514
50                         Sierra Leone     7017.153     7171.909     7328.846
51                                 Togo     7137.997     7323.162     7509.952
52                              Algeria    38923.688    39728.020    40551.398
53                                Egypt    90424.668    92442.549    94447.071
54                                Libya     6362.039     6418.315     6492.160
55                              Morocco    34192.358    34663.608    35126.274
56                                Sudan    37977.657    38902.948    39847.433
57                              Tunisia    11063.195    11179.951    11303.942
58                       Western Sahara      514.984      526.211      538.744
59                              Armenia     2912.403     2925.559     2936.147
60                           Azerbaijan     9505.616     9622.741     9736.041
61                              Bahrain     1336.073     1371.853     1425.793
62                               Cyprus     1152.297     1160.987     1170.189
63                              Georgia     4035.310     4024.180     4015.457
64                                 Iraq    34411.949    35572.269    36610.632
65                               Israel     7854.216     7978.496     8108.984
66                               Jordan     8918.822     9266.573     9554.286
67                               Kuwait     3690.939     3835.588     3956.862
68                              Lebanon     6261.046     6532.681     6714.281
69                                 Oman     4027.255     4267.341     4479.217
70                                Qatar     2459.202     2565.708     2654.379
71                         Saudi Arabia    30916.603    31717.676    32443.443
72                   State of Palestine     4428.634     4529.160     4635.644
73                 Syrian Arab Republic    18710.711    17997.411    17465.567
74                               Turkey    77229.262    78529.413    79827.868
75                 United Arab Emirates     9214.182     9262.896     9360.975
76                                Yemen    25823.488    26497.881    27168.210
77                           Kazakhstan    17302.619    17572.010    17830.902
78                           Kyrgyzstan     5844.521     5959.126     6074.327
79                           Tajikistan     8252.828     8454.019     8663.575
80                         Turkmenistan     5466.324     5565.283     5662.371
81                           Uzbekistan    30426.394    30929.556    31441.753
82                          Afghanistan    33370.804    34413.603    35383.028
83                           Bangladesh   154517.385   156256.287   157977.151
84                               Bhutan      719.053      727.885      736.706
85                                India  1295600.768  1310152.392  1324517.250
86           Iran (Islamic Republic of)    77465.769    78492.208    79563.991
87                             Maldives      435.018      454.914      475.505
88                                Nepal    26905.982    27015.033    27263.430
89                             Pakistan   195305.012   199426.953   203631.356
90                            Sri Lanka    20788.512    20908.024    21021.177
91                                China  1399453.966  1406847.868  1414049.353
92                 China, Hong Kong SAR     7134.668     7185.992     7243.541
93                     China, Macao SAR      590.210      602.093      612.824
94      China, Taiwan Province of China    23491.976    23557.473    23618.201
95      Dem. People's Republic of Korea    25057.793    25183.832    25307.665
96                                Japan   128168.630   127985.139   127763.267
97                             Mongolia     2940.111     2998.433     3056.358
98                    Republic of Korea    50607.904    50823.087    50983.446
99                    Brunei Darussalam      409.778      414.914      419.791
100                            Cambodia    15274.506    15521.435    15766.290
101                           Indonesia   255128.076   258383.257   261556.386
102    Lao People's Democratic Republic     6639.763     6741.160     6845.848
103                            Malaysia    29866.606    30270.965    30684.652
104                             Myanmar    52280.816    52680.724    53045.199
105                         Philippines   100513.137   102113.206   103663.812
106                           Singapore     5525.628     5592.143     5653.625
107                            Thailand    68438.748    68714.519    68971.313
108                         Timor-Leste     1174.333     1196.294     1219.289
109                            Viet Nam    91713.850    92677.082    93640.435
110                            Anguilla       14.114       14.279       14.435
111                 Antigua and Barbuda       92.562       93.571       94.520
112                               Aruba      103.776      104.339      104.865
113                             Bahamas      370.625      374.200      377.923
114                            Barbados      284.825      285.327      285.798
115    Bonaire, Sint Eustatius and Saba       24.067       24.571       25.017
116              British Virgin Islands       28.985       29.148       29.355
117                      Cayman Islands       60.848       61.721       62.564
118                                Cuba    11306.909    11324.777    11335.108
119                             CuraÃ§ao      158.432      159.850      161.055
120                            Dominica       71.091       71.175       71.307
121                  Dominican Republic    10165.182    10281.675    10397.738
122                             Grenada      108.900      109.603      110.263
123                          Guadeloupe      401.305      400.260      399.760
124                               Haiti    10549.007    10695.540    10839.976
125                             Jamaica     2875.137     2891.024     2906.242
126                          Martinique      381.142      378.483      376.789
127                          Montserrat        4.952        4.966        4.978
128                         Puerto Rico     3453.667     3381.512     3283.121
129                    Saint BarthÃ©lemy        9.620        9.696        9.745
130               Saint Kitts and Nevis       50.776       51.204       51.629
131                         Saint Lucia      178.307      179.131      180.028
132          Saint Martin (French part)       36.018       35.865       36.061
133    Saint Vincent and the Grenadines      108.868      109.135      109.467
134           Sint Maarten (Dutch part)       38.872       39.967       40.812
135                 Trinidad and Tobago     1362.337     1370.332     1377.563
136            Turks and Caicos Islands       35.371       35.979       36.558
137        United States Virgin Islands      105.107      104.950      104.829
138                              Belize      353.366      360.926      368.399
139                          Costa Rica     4795.390     4847.805     4899.336
140                         El Salvador     6295.124     6325.121     6356.137
141                           Guatemala    15923.238    16252.425    16583.079
142                            Honduras     8955.579     9112.904     9270.794
143                              Mexico   120355.137   121858.251   123333.379
144                           Nicaragua     6142.734     6223.234     6303.970
145                              Panama     3901.311     3968.490     4037.073
146                           Argentina    42637.508    43075.416    43508.459
147    Bolivia (Plurinational State of)    10706.517    10869.732    11031.822
148                              Brazil   202763.744   204471.759   206163.056
149                               Chile    17758.969    17969.356    18209.072
150                            Colombia    46967.706    47520.667    48175.048
151                             Ecuador    15951.832    16212.022    16491.116
152         Falkland Islands (Malvinas)        2.787        2.836        2.926
153                       French Guiana      254.780      261.008      267.824
154                              Guyana      763.371      767.433      771.363
155                            Paraguay     6599.524     6688.746     6777.878
156                                Peru    30090.372    30470.739    30926.036
157                            Suriname      553.278      559.136      564.883
158                             Uruguay     3400.439     3412.013     3424.139
159  Venezuela (Bolivarian Republic of)    30042.973    30081.827    29851.249
160                           Australia    23596.426    23932.499    24262.710
161                         New Zealand     4567.522     4614.527     4659.265
162                                Fiji      866.447      868.632      872.406
163                       New Caledonia      267.732      271.062      274.190
164                    Papua New Guinea     7946.733     8107.772     8271.766
165                     Solomon Islands      587.079      603.133      619.438
166                             Vanuatu      263.888      271.128      278.326
167                                Guam      161.007      161.851      162.948
168                            Kiribati      109.387      110.927      112.529
169                    Marshall Islands       57.183       57.444       57.723
170         Micronesia (Fed. States of)      107.444      108.886      110.215
171                               Nauru       10.289       10.374       10.474
172            Northern Mariana Islands       55.301       55.779       56.187
173                               Palau       17.625       17.665       17.718
174                      American Samoa       55.791       55.806       55.739
175                        Cook Islands       17.685       17.581       17.521
176                    French Polynesia      271.713      273.119      274.576
177                                Niue        1.607        1.610        1.611
178                               Samoa      192.220      193.510      194.540
179                             Tokelau        1.217        1.247        1.276
180                               Tonga      101.023      100.780      101.143
181                              Tuvalu       10.973       11.099       11.232
182           Wallis and Futuna Islands       12.338       12.262       12.098
183                             Belarus     9431.742     9439.424     9445.638
184                            Bulgaria     7245.648     7199.739     7151.948
185                             Czechia    10591.104    10601.390    10618.868
186                             Hungary     9804.991     9777.925     9752.970
187                              Poland    38091.095    38034.076    37989.218
188                 Republic of Moldova     4073.407     4070.705     4066.013
189                             Romania    20035.928    19925.182    19796.280
190                  Russian Federation   144664.837   144985.059   145275.374
191                            Slovakia     5428.798     5435.614     5442.001
192                             Ukraine    45111.530    44921.636    44713.708
193                     Channel Islands      164.107      165.387      166.922
194                             Denmark     5664.199     5688.695     5711.346
195                             Estonia     1316.273     1315.330     1316.507
196                       Faroe Islands       47.965       48.055       48.173
197                             Finland     5461.410     5481.128     5497.714
198                             Iceland      328.592      330.237      332.209
199                             Ireland     4626.852     4652.420     4695.790
200                         Isle of Man       83.488       83.232       83.296
201                              Latvia     2021.220     1997.675     1974.265
202                           Lithuania     2971.498     2931.872     2889.555
203                              Norway     5142.269     5199.827     5250.950
204                              Sweden     9692.137     9764.949     9836.003
205                      United Kingdom    65423.048    65860.149    66297.944
206                             Albania     2896.307     2890.524     2886.427
207                             Andorra       79.213       77.993       77.295
208              Bosnia and Herzegovina     3482.106     3429.362     3386.263
209                             Croatia     4255.518     4232.874     4208.611
210                           Gibraltar       33.726       33.742       33.738
211                              Greece    10701.460    10659.737    10615.183
212                            Holy See        0.785        0.790        0.791
213                               Italy    60409.622    60578.489    60663.068
214                               Malta      430.190      433.559      436.099
215                          Montenegro      626.650      626.957      627.271
216                     North Macedonia     2077.780     2079.335     2080.746
217                            Portugal    10418.224    10368.346    10325.540
218                          San Marino       32.941       33.270       33.503
219                              Serbia     8898.284     8876.777     8853.963
220                            Slovenia     2067.488     2071.199     2074.205
221                               Spain    46777.927    46671.919    46634.131
222                             Austria     8615.205     8678.667     8747.306
223                             Belgium    11221.225    11287.931    11354.407
224                              France    64193.550    64453.194    64667.590
225                             Germany    81450.370    81787.411    82193.770
226                       Liechtenstein       37.219       37.465       37.655
227                          Luxembourg      554.512      566.741      579.266
228                              Monaco       37.320       37.723       38.070
229                         Netherlands    16892.517    16938.492    16981.285
230                         Switzerland     8206.003     8296.775     8379.915
231                             Bermuda       64.038       63.695       63.360
232                              Canada    35664.338    36026.668    36382.942
233                           Greenland       56.383       56.378       56.408
234           Saint Pierre and Miquelon        6.073        5.992        5.933
235            United States of America   318673.422   320878.312   323015.992

In [8]:
# Merge Population Data
# Merge centroid lon, lat 
ebola_3 = pd.merge(ebola_2, pop_data_1, on='Country', how = 'left')
ebola_3

                     Country  year  No_of_confirmed_cases  No_of_confirmed_deaths            name  Longitude   Latitude        2014        2015        2016
0                     Guinea  2014                56295.0                 31014.0          Guinea -10.940666  10.436216   11150.970   11432.096   11738.434
1                     Guinea  2015               689976.0                428114.0          Guinea -10.940666  10.436216   11150.970   11432.096   11738.434
2                     Guinea  2016                 3351.0                  2083.0          Guinea -10.940666  10.436216   11150.970   11432.096   11738.434
3                      Italy  2015                  140.0                     0.0           Italy  12.070013  42.796626   60409.622   60578.489   60663.068
4                      Italy  2016                    1.0                     0.0           Italy  12.070013  42.796626   60409.622   60578.489   60663.068
5                    Liberia  2014                72254.0                 11385.0         Liberia  -9.322076   6.452785    4359.508    4472.229    4586.788
6                    Liberia  2015               693322.0                 15548.0         Liberia  -9.322076   6.452785    4359.508    4472.229    4586.788
7                    Liberia  2016                 3162.0                     4.0         Liberia  -9.322076   6.452785    4359.508    4472.229    4586.788
8                       Mali  2014                  111.0                    21.0            Mali  -3.542691  17.345816   16934.213   17438.772   17965.448
9                       Mali  2015                 1540.0                     0.0            Mali  -3.542691  17.345816   16934.213   17438.772   17965.448
10                      Mali  2016                    7.0                     0.0            Mali  -3.542691  17.345816   16934.213   17438.772   17965.448
11                   Nigeria  2014                  717.0                   265.0         Nigeria   8.089439   9.594115  176404.931  181137.454  185960.244
12                   Nigeria  2015                 4104.0                  1512.0         Nigeria   8.089439   9.594115  176404.931  181137.454  185960.244
13                   Nigeria  2016                   19.0                     7.0         Nigeria   8.089439   9.594115  176404.931  181137.454  185960.244
14                   Senegal  2014                   37.0                     0.0         Senegal -14.473492  14.366242   14174.740   14578.450   14993.514
15                   Senegal  2015                  216.0                     0.0         Senegal -14.473492  14.366242   14174.740   14578.450   14993.514
16                   Senegal  2016                    1.0                     0.0         Senegal -14.473492  14.366242   14174.740   14578.450   14993.514
17              Sierra Leone  2014               156787.0                 41981.0    Sierra Leone -11.792712   8.563296    7017.153    7171.909    7328.846
18              Sierra Leone  2015              1876380.0                752414.0    Sierra Leone -11.792712   8.563296    7017.153    7171.909    7328.846
19              Sierra Leone  2016                 8704.0                  3589.0    Sierra Leone -11.792712   8.563296    7017.153    7171.909    7328.846
20                     Spain  2014                   26.0                     0.0           Spain  -3.647550  40.244487   46777.927   46671.919   46634.131
21                     Spain  2015                  216.0                     0.0           Spain  -3.647550  40.244487   46777.927   46671.919   46634.131
22                     Spain  2016                    1.0                     0.0           Spain  -3.647550  40.244487   46777.927   46671.919   46634.131
23            United Kingdom  2015                  220.0                     0.0  United Kingdom  -2.865632  54.123872   65423.048   65860.149   66297.944
24            United Kingdom  2016                    1.0                     0.0  United Kingdom  -2.865632  54.123872   65423.048   65860.149   66297.944
25  United States of America  2014                   99.0                    25.0             NaN        NaN        NaN  318673.422  320878.312  323015.992
26  United States of America  2015                  864.0                   216.0             NaN        NaN        NaN  318673.422  320878.312  323015.992
27  United States of America  2016                    4.0                     1.0             NaN        NaN        NaN  318673.422  320878.312  323015.992

In [ ]:
# Add population column
ebola_3['population'] = ebola_3['2014'] * 1000
ebola_3['population'] = np.where(ebola_3['year'] == 2015, ebola_3['2015'], ebola_3['population'] * 1000)
ebola_3['population'] = np.where(ebola_3['year'] == 2016, ebola_3['2016'], ebola_3['population'] * 1000)
ebola_3['Pandemic'] = "Ebola"
ebola_3

In [ ]:
# Get columns in following order: Pandemic, Country, Year, Cases, Deaths, lon,lat, population
ebola_4 = ebola_3[['Pandemic', 'Country', 'year', 'No_of_confirmed_cases', 'No_of_confirmed_deaths', 'Longitude', 'Latitude', 'population']]
ebola_5 = ebola_4.rename(columns={"year": "Year", "Longitude": "Lon", "Latitude": "Lat", "No_of_confirmed_cases": "Cases", "No_of_confirmed_deaths": "Deaths"  })
ebola_5

In [ ]:
# Save scrubbed file to .csv
ebola_5.to_csv(r'Data/ebola_data.csv', index = False, header=True)