### Notebook to create dataset from United Nations Population Data (Country, Pop. by Year from 2009 to 2020) and Country_Centroids Data (Country, Lat, Lon)

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
population_data_to_load = "Data/WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx"

# Read Population Data from "Estimates" sheet
population_data = pd.read_excel(population_data_to_load, "ESTIMATES", encoding="ISO-8859-1")

In [2]:
population_data.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United Nations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Population Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Department of Economic and Social Affairs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,World Population Prospects 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,File POP/1-1: Total population (both sexes com...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"Estimates, 1950 - 2020",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,POP/DB/WPP/Rev.2019/POP/F01-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"© August 2019 by United Nations, made availabl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"Suggested citation: United Nations, Department...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Total population, both sexes combined, as of 1...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Index,Variant,"Region, subregion, country or area *",Notes,Country code,Type,Parent code,1950,1951,1952,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
16,1,Estimates,WORLD,NaN,900,World,0,2.53643e+06,2.58403e+06,2.63086e+06,...,7.04119e+06,7.12583e+06,7.21058e+06,7.29529e+06,7.3798e+06,7.46402e+06,7.54786e+06,7.63109e+06,7.71347e+06,7.7948e+06
17,2,Estimates,UN development groups,a,1803,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,3,Estimates,More developed regions,b,901,Development Group,1803,814819,824004,833720,...,1.23956e+06,1.24411e+06,1.24845e+06,1.25262e+06,1.25662e+06,1.26048e+06,1.26415e+06,1.26756e+06,1.27063e+06,1.2733e+06
19,4,Estimates,Less developed regions,c,902,Development Group,1803,1.72161e+06,1.76003e+06,1.79714e+06,...,5.80164e+06,5.88171e+06,5.96213e+06,6.04268e+06,6.12317e+06,6.20354e+06,6.28371e+06,6.36353e+06,6.44284e+06,6.52149e+06

In [9]:
# Remove rows with "NaN" in Unnamed: 2
pop_data_1 = population_data[pd.notnull(population_data["Unnamed: 2"])]
pop_data_1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
15,Index,Variant,"Region, subregion, country or area *",Notes,Country code,Type,Parent code,1950,1951,1952,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
16,1,Estimates,WORLD,NaN,900,World,0,2.53643e+06,2.58403e+06,2.63086e+06,...,7.04119e+06,7.12583e+06,7.21058e+06,7.29529e+06,7.3798e+06,7.46402e+06,7.54786e+06,7.63109e+06,7.71347e+06,7.7948e+06
17,2,Estimates,UN development groups,a,1803,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,3,Estimates,More developed regions,b,901,Development Group,1803,814819,824004,833720,...,1.23956e+06,1.24411e+06,1.24845e+06,1.25262e+06,1.25662e+06,1.26048e+06,1.26415e+06,1.26756e+06,1.27063e+06,1.2733e+06
19,4,Estimates,Less developed regions,c,902,Development Group,1803,1.72161e+06,1.76003e+06,1.79714e+06,...,5.80164e+06,5.88171e+06,5.96213e+06,6.04268e+06,6.12317e+06,6.20354e+06,6.28371e+06,6.36353e+06,6.44284e+06,6.52149e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,285,Estimates,Bermuda,14,60,Country/Area,918,37.256,37.8,38.437,...,65.076,64.737,64.381,64.038,63.695,63.36,63.04,62.763,62.508,62.273
301,286,Estimates,Canada,NaN,124,Country/Area,918,13733.4,14078.4,14445.5,...,34539.2,34922,35296.5,35664.3,36026.7,36382.9,36732.1,37074.6,37411,37742.2
302,287,Estimates,Greenland,26,304,Country/Area,918,22.993,23.466,23.936,...,56.555,56.477,56.412,56.383,56.378,56.408,56.473,56.565,56.66,56.772
303,288,Estimates,Saint Pierre and Miquelon,2,666,Country/Area,918,4.567,4.609,4.648,...,6.323,6.251,6.168,6.073,5.992,5.933,5.885,5.845,5.821,5.795
304,289,Estimates,United States of America,35,840,Country/Area,918,158804,160872,163266,...,311584,314044,316401,318673,320878,323016,325085,327096,329065,331003

In [10]:
# Select columns we want to keep
pop_data_2 = pd.DataFrame(pop_data_1, columns = ['Unnamed: 2', 'Unnamed: 5', 'Unnamed: 66', 
                                                 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69',
                                                 'Unnamed: 70','Unnamed: 71', 'Unnamed: 72',
                                                 'Unnamed: 73', 'Unnamed: 74','Unnamed: 75', 
                                                 'Unnamed: 76','Unnamed: 77',]).copy()

In [11]:
pop_data_3 = pop_data_2.rename(columns={"Unnamed: 2": "Country", "Unnamed: 5": "Type", "Unnamed: 66": "2009", 
                                       'Unnamed: 67': "2010", 'Unnamed: 68': "2011", 'Unnamed: 69': "2012",
                                       'Unnamed: 70': "2013", 'Unnamed: 71': "2014", 'Unnamed: 72': "2015",
                                       'Unnamed: 73': "2016", 'Unnamed: 74': "2017", 'Unnamed: 75': "2018",
                                       'Unnamed: 76': "2019", 'Unnamed: 77': "2020"})
pop_data_3

,Country,Type,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
15,"Region, subregion, country or area *",Type,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
16,WORLD,World,6.87277e+06,6.95682e+06,7.04119e+06,7.12583e+06,7.21058e+06,7.29529e+06,7.3798e+06,7.46402e+06,7.54786e+06,7.63109e+06,7.71347e+06,7.7948e+06
17,UN development groups,Label/Separator,...,...,...,...,...,...,...,...,...,...,...,...
18,More developed regions,Development Group,1.22974e+06,1.23477e+06,1.23956e+06,1.24411e+06,1.24845e+06,1.25262e+06,1.25662e+06,1.26048e+06,1.26415e+06,1.26756e+06,1.27063e+06,1.2733e+06
19,Less developed regions,Development Group,5.64303e+06,5.72206e+06,5.80164e+06,5.88171e+06,5.96213e+06,6.04268e+06,6.12317e+06,6.20354e+06,6.28371e+06,6.36353e+06,6.44284e+06,6.52149e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,Bermuda,Country/Area,65.675,65.388,65.076,64.737,64.381,64.038,63.695,63.36,63.04,62.763,62.508,62.273
301,Canada,Country/Area,33746.1,34147.6,34539.2,34922,35296.5,35664.3,36026.7,36382.9,36732.1,37074.6,37411,37742.2
302,Greenland,Country/Area,56.729,56.638,56.555,56.477,56.412,56.383,56.378,56.408,56.473,56.565,56.66,56.772
303,Saint Pierre and Miquelon,Country/Area,6.343,6.361,6.323,6.251,6.168,6.073,5.992,5.933,5.885,5.845,5.821,5.795
304,United States of America,Country/Area,306308,309011,311584,314044,316401,318673,320878,323016,325085,327096,329065,331003

In [17]:
# Keep only world and country rows
pop_data_4 = pop_data_3.loc[pop_data_3['Type'].isin(['Country/Area','World'])]
pop_data_4

,Country,Type,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
16,WORLD,World,6.87277e+06,6.95682e+06,7.04119e+06,7.12583e+06,7.21058e+06,7.29529e+06,7.3798e+06,7.46402e+06,7.54786e+06,7.63109e+06,7.71347e+06,7.7948e+06
42,Burundi,Country/Area,8397.66,8675.61,8958.41,9245.99,9540.3,9844.3,10160,10488,10827,11175.4,11530.6,11890.8
43,Comoros,Country/Area,673.251,689.696,706.578,723.865,741.511,759.39,777.435,795.597,813.89,832.322,850.891,869.595
44,Djibouti,Country/Area,827.82,840.194,853.671,868.136,883.296,898.707,913.998,929.117,944.1,958.923,973.557,988.002
45,Eritrea,Country/Area,3119.92,3170.44,3213.97,3250.1,3281.45,3311.44,3342.82,3376.56,3412.89,3452.8,3497.12,3546.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,Bermuda,Country/Area,65.675,65.388,65.076,64.737,64.381,64.038,63.695,63.36,63.04,62.763,62.508,62.273
301,Canada,Country/Area,33746.1,34147.6,34539.2,34922,35296.5,35664.3,36026.7,36382.9,36732.1,37074.6,37411,37742.2
302,Greenland,Country/Area,56.729,56.638,56.555,56.477,56.412,56.383,56.378,56.408,56.473,56.565,56.66,56.772
303,Saint Pierre and Miquelon,Country/Area,6.343,6.361,6.323,6.251,6.168,6.073,5.992,5.933,5.885,5.845,5.821,5.795
304,United States of America,Country/Area,306308,309011,311584,314044,316401,318673,320878,323016,325085,327096,329065,331003

In [24]:
# Save scrubbed pop file to .csv
pop_data_4.to_csv(r'Data/pop_data_2009-2019.csv', index = False, header=True)